export const EARTH_RADIUS_KM = 6371.0088;

const DEG2RAD = Math.PI / 180;
const RAD2DEG = 180 / Math.PI;

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

export function normalizeLongitude(longitude) {
  const value = Number(longitude);
  return ((value + 540) % 360) - 180;
}

/**
 * Authoritative pure-math geographic frame for Traveling.
 * Longitude is east-positive, +Y is north, and -Z points east from lon=0.
 * No DOM, SVG, Canvas or Three.js transform is applied here.
 */
export function geographicToCartesian(latitude, longitude, radius = 1) {
  const lat = clamp(Number(latitude), -90, 90) * DEG2RAD;
  const lng = normalizeLongitude(longitude) * DEG2RAD;
  const cosLat = Math.cos(lat);
  return {
    x: radius * cosLat * Math.cos(lng),
    y: radius * Math.sin(lat),
    z: -radius * cosLat * Math.sin(lng)
  };
}

export function cartesianToGeographic(point) {
  const x = Number(point?.x) || 0;
  const y = Number(point?.y) || 0;
  const z = Number(point?.z) || 0;
  const radius = Math.max(Math.hypot(x, y, z), Number.EPSILON);
  const latitude = Math.asin(clamp(y / radius, -1, 1)) * RAD2DEG;
  const longitude = Math.atan2(-z, x) * RAD2DEG;
  return { latitude, longitude: normalizeLongitude(longitude) };
}

export function haversineKm(latA, lngA, latB, lngB) {
  const phi1 = Number(latA) * DEG2RAD;
  const phi2 = Number(latB) * DEG2RAD;
  const deltaPhi = phi2 - phi1;
  const deltaLambda = normalizeLongitude(Number(lngB) - Number(lngA)) * DEG2RAD;
  const a = Math.sin(deltaPhi / 2) ** 2
    + Math.cos(phi1) * Math.cos(phi2) * Math.sin(deltaLambda / 2) ** 2;
  return 2 * EARTH_RADIUS_KM * Math.asin(Math.min(1, Math.sqrt(a)));
}

function circularMeanLongitude(ring) {
  let x = 0;
  let y = 0;
  for (const [longitude] of ring) {
    const radians = normalizeLongitude(longitude) * DEG2RAD;
    x += Math.cos(radians);
    y += Math.sin(radians);
  }
  return Math.atan2(y, x) * RAD2DEG;
}

function unwrapLongitude(longitude, anchor) {
  let value = normalizeLongitude(longitude);
  while (value - anchor > 180) value -= 360;
  while (value - anchor < -180) value += 360;
  return value;
}

export function unwrapRing(ring, anchor = null) {
  if (!Array.isArray(ring) || ring.length < 3) return [];
  const source = ring.slice();
  const firstRaw = source[0];
  const lastRaw = source.at(-1);
  // GeoJSON often repeats the initial point. Removing it prevents a second,
  // accidental closing segment from being generated by the border renderer.
  if (
    source.length > 3
    && normalizeLongitude(firstRaw[0]) === normalizeLongitude(lastRaw[0])
    && Number(firstRaw[1]) === Number(lastRaw[1])
  ) source.pop();

  const first = [normalizeLongitude(source[0][0]), Number(source[0][1])];
  const unwrapped = [first];
  for (const [longitude, latitude] of source.slice(1)) {
    let nextLongitude = normalizeLongitude(longitude);
    const previousLongitude = unwrapped.at(-1)[0];
    // Unwrap relative to the preceding point, not a global average. This keeps
    // every edge under 180° and prevents antimeridian tears across the globe.
    while (nextLongitude - previousLongitude > 180) nextLongitude -= 360;
    while (nextLongitude - previousLongitude < -180) nextLongitude += 360;
    unwrapped.push([nextLongitude, Number(latitude)]);
  }

  if (anchor === null) return unwrapped;
  const center = unwrapped.reduce((sum, [longitude]) => sum + longitude, 0) / unwrapped.length;
  const offset = Math.round((anchor - center) / 360) * 360;
  return unwrapped.map(([longitude, latitude]) => [longitude + offset, latitude]);
}

function ringBounds(ring) {
  let minLongitude = Infinity;
  let maxLongitude = -Infinity;
  let minLatitude = Infinity;
  let maxLatitude = -Infinity;
  for (const [longitude, latitude] of ring) {
    minLongitude = Math.min(minLongitude, longitude);
    maxLongitude = Math.max(maxLongitude, longitude);
    minLatitude = Math.min(minLatitude, latitude);
    maxLatitude = Math.max(maxLatitude, latitude);
  }
  return { minLongitude, maxLongitude, minLatitude, maxLatitude };
}

export function pointInRing(longitude, latitude, ring) {
  if (ring.length < 3) return false;
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const edgeCrossesLatitude = (yi > latitude) !== (yj > latitude);
    if (!edgeCrossesLatitude) continue;
    const denominator = yj - yi;
    const edgeLongitude = ((xj - xi) * (latitude - yi)) / (Math.abs(denominator) < 1e-12 ? 1e-12 : denominator) + xi;
    if (longitude < edgeLongitude) inside = !inside;
  }
  return inside;
}

export function prepareGeoPolygon(polygon) {
  if (!Array.isArray(polygon) || !polygon[0]?.length) return null;
  const anchor = circularMeanLongitude(polygon[0]);
  const outer = unwrapRing(polygon[0], anchor);
  const holes = polygon.slice(1).map(ring => unwrapRing(ring, anchor));
  return { anchor, outer, holes, ...ringBounds(outer) };
}

export function preparedPolygonContains(prepared, latitude, longitude) {
  if (!prepared) return false;
  const queryLongitude = unwrapLongitude(longitude, prepared.anchor);
  if (
    queryLongitude < prepared.minLongitude
    || queryLongitude > prepared.maxLongitude
    || latitude < prepared.minLatitude
    || latitude > prepared.maxLatitude
  ) return false;
  if (!pointInRing(queryLongitude, latitude, prepared.outer)) return false;
  return !prepared.holes.some(hole => pointInRing(queryLongitude, latitude, hole));
}

export function geometryToPolygons(geometry) {
  if (!geometry) return [];
  if (geometry.type === 'Polygon') return [geometry.coordinates];
  if (geometry.type === 'MultiPolygon') return geometry.coordinates;
  return [];
}

export function prepareGeometry(geometry) {
  return geometryToPolygons(geometry).map(prepareGeoPolygon).filter(Boolean);
}

export function preparedGeometryContains(preparedPolygons, latitude, longitude) {
  return preparedPolygons.some(polygon => preparedPolygonContains(polygon, latitude, longitude));
}

export function createRafThrottle(callback, minimumIntervalMs = 24) {
  let frameId = 0;
  let lastExecution = -Infinity;
  let pendingArgs = null;
  const run = timestamp => {
    frameId = 0;
    if (!pendingArgs) return;
    if (timestamp - lastExecution < minimumIntervalMs) {
      frameId = requestAnimationFrame(run);
      return;
    }
    const args = pendingArgs;
    pendingArgs = null;
    lastExecution = timestamp;
    callback(...args);
  };
  const throttled = (...args) => {
    pendingArgs = args;
    if (!frameId) frameId = requestAnimationFrame(run);
  };
  throttled.cancel = () => {
    pendingArgs = null;
    if (frameId) cancelAnimationFrame(frameId);
    frameId = 0;
  };
  return throttled;
}
