export const MILES_TABS = Object.freeze([
  { key: 'overview', label: 'Visão geral' },
  { key: 'cards', label: 'Cartões' },
  { key: 'lounges', label: 'Salas VIP' },
  { key: 'upgrades', label: 'Upgrades' },
  { key: 'airports', label: 'Aeroportos' }
]);

export const LEARNING_PATHS = Object.freeze([
  {
    id: 'earn', title: 'Acumular',
    summary: 'Como cartões, compras e transferências viram pontos e milhas.',
    lessons: [
      'Pontos nascem em bancos, cartões ou compras; milhas ficam em programas de fidelidade de companhias aéreas. O nome varia conforme o programa.',
      'Pontos transferíveis podem ser enviados a diferentes parceiros. Manter opções abertas ajuda a esperar por um resgate que faça sentido.',
      'A taxa de acúmulo diz quantos pontos você recebe por valor gasto. Compare também anuidade, categorias que pontuam e validade dos pontos.',
      'Um cartão de companhia aérea pode oferecer vantagens nessa empresa, mas concentra seu saldo e sua escolha de viagens.',
      'Bônus de transferência aumenta o saldo enviado sob regras e prazos específicos. Transferir sem viagem definida traz risco de expiração, mudança de tabela e falta de assentos.'
    ]
  },
  {
    id: 'redeem', title: 'Usar melhor',
    summary: 'Como avaliar um resgate, bônus de transferência e valor por ponto.',
    lessons: [
      'Resgate é a emissão de uma viagem com pontos ou milhas. Compare com a passagem em dinheiro que você realmente compraria.',
      'Valor por ponto (CPP, em centavos) = (preço em dinheiro evitado − taxas do resgate) × 100 ÷ pontos usados. Use a mesma moeda nas duas parcelas.',
      'Taxas, impostos e eventuais cobranças do programa podem mudar a comparação. Veja o custo total antes de transferir.',
      'Assentos para resgate são limitados e podem não existir em certas datas ou voos; um assento à venda não garante um assento por milhas.',
      'O preço em milhas pode ser dinâmico: o mesmo trajeto pode custar valores diferentes conforme data, procura e disponibilidade.'
    ]
  },
  {
    id: 'travel', title: 'Viajar melhor',
    summary: 'Salas VIP, upgrades, Fast Track e benefícios nos aeroportos.',
    lessons: [
      'Uma sala VIP depende do seu benefício, da rede aceita e do terminal do seu voo. Confira visitas e convidados antes de ir.',
      'Upgrade pode ser pago, oferecido no check-in, solicitado com milhas ou ligado a status. Regras e disponibilidade variam por companhia.',
      'Fast Track e outros serviços de aeroporto dependem de local, companhia e benefício contratado. Confirme a regra para seu itinerário.'
    ]
  }
]);

export const CARD_PROFILES = Object.freeze([
  { id: 'lounges', label: 'Para salas VIP', guidance: 'Compare rede aceita, visitas incluídas, convidados, terminais e condições de uso.' },
  { id: 'earn', label: 'Para acumular pontos', guidance: 'Compare taxa de acúmulo, parceiros de transferência, validade e custo anual.' },
  { id: 'airline', label: 'Para companhias aéreas', guidance: 'Avalie se você realmente voa com a companhia e usará os benefícios específicos.' },
  { id: 'travel', label: 'Para benefícios de viagem', guidance: 'Considere seguro, bagagem, serviços de aeroporto e condições de elegibilidade.' }
]);

// Dados consultados nas páginas oficiais em 2026-09. Benefícios são condicionais;
// taxas e elegibilidade devem ser reconfirmadas antes da contratação.
export const CARD_OFFERS = Object.freeze([
  { id: 'santander-unlimited', name: 'Santander Unlimited', issuer: 'Santander', network: 'Mastercard Black ou Visa Infinite', profile: 'lounges', tags: ['Foco em lounges', 'Alta exigência'], earning: '3 pontos/US$ em compras nacionais; 3,6 no exterior (Select)', loyaltyProgram: 'Esfera', loungeAccess: 'LoungeKey ou Visa Airport Companion: acessos ilimitados do titular; 8 acessos de convidados/ano, conforme variante', annualFee: '12 × R$ 183,33', feeWaiver: 'Gasto de R$ 30 mil/fatura ou R$ 5 milhões investidos', guests: '8 acessos anuais para convidados do titular', travelBenefits: 'Pontos Esfera sem expiração; benefícios da bandeira', idealFor: 'Viajantes frequentes que usam salas e atingem a regra de isenção', officialSource: 'https://www.santander.com.br/cartao-credito-santander/unlimited', verifiedAt: '2026-09', status: 'verified' },
  { id: 'itau-the-one', name: 'The One', issuer: 'Itaú Personnalité', network: 'Mastercard Black', profile: 'lounges', tags: ['Foco em lounges', 'Benefícios premium', 'Anuidade elevada'], earning: '3 pontos/US$ no Brasil; 3,5 no exterior', loyaltyProgram: 'Itaú Pontos', loungeAccess: 'LoungeKey: acessos gratuitos ilimitados para titular e adicionais', guests: '12 acessos de convidados/ano', annualFee: '12 × R$ 333,34 (R$ 4.000/ano, conforme página do banco)', feeWaiver: '100% com R$ 5 milhões investidos, R$ 60 mil/fatura ou nível 5 Minhas Vantagens; 50% com R$ 30–59,9 mil/fatura', travelBenefits: 'Pontos sem expiração; salas Mastercard no GRU', idealFor: 'Cliente Personnalité com viagens internacionais frequentes', officialSource: 'https://www.itau.com.br/personnalite/cartoes/theone', verifiedAt: '2026-09', status: 'verified' },
  { id: 'itau-personnalite-black', name: 'Personnalité Mastercard Black Pontos', issuer: 'Itaú', network: 'Mastercard Black', profile: 'earn', tags: ['Bom para acúmulo geral', 'Custo/anuidade'], earning: '2 pontos/US$ no Brasil; 3 no exterior', loyaltyProgram: 'Itaú Pontos, transferíveis a programas parceiros', loungeAccess: '2 visitas LoungeKey/ano; salas Mastercard GRU ilimitadas', annualFee: 'R$ 1.056/ano', feeWaiver: 'R$ 50 mil investidos, R$ 10 mil/fatura ou nível 2+ no Minhas Vantagens', travelBenefits: 'Pontos sem expiração; benefícios Mastercard Black', idealFor: 'Quem quer pontos flexíveis e consegue isenção', officialSource: 'https://www.itau.com.br/personnalite/cartoes/personnalite-mastercard-black', verifiedAt: '2026-09', status: 'verified' },
  { id: 'santander-unique', name: 'Santander Unique Pontos', issuer: 'Santander', network: 'Mastercard Black ou Visa Infinite', profile: 'earn', tags: ['Acúmulo geral', 'Salas VIP'], earning: '2,2 pontos Esfera/US$ no Brasil; 3 no exterior', loyaltyProgram: 'Esfera', loungeAccess: '2 visitas anuais em salas da rede da variante elegível', annualFee: 'Após 3 meses gratuitos, 12 × R$ 96,25', feeWaiver: 'Até 100% cumprindo 2 critérios: conta com pacote ativo, R$ 8 mil/fatura ou R$ 50 mil investidos', travelBenefits: 'Benefícios da bandeira e transferência de pontos Esfera', idealFor: 'Quem concentra gastos no Santander e prefere flexibilidade', officialSource: 'https://www.santander.com.br/banco/unique', verifiedAt: '2026-09', status: 'verified' },
  { id: 'latam-visa-infinite', name: 'LATAM Pass Visa Infinite', issuer: 'Itaú', network: 'Visa Infinite', profile: 'airline', tags: ['Bom para LATAM', 'Benefícios internacionais'], earning: '2,5 milhas/US$ no Brasil; 3,5 no exterior', loyaltyProgram: 'LATAM Pass', loungeAccess: '2 visitas Visa Airport Companion/ano; LATAM lounges ao voar LATAM, conforme regras', annualFee: 'R$ 113/mês abaixo de R$ 10 mil em gastos', feeWaiver: '50% a partir de R$ 10 mil/fatura; 100% a partir de R$ 20 mil/fatura', travelBenefits: 'Trechos de upgrade de cortesia e benefícios LATAM Pass', idealFor: 'Quem voa regularmente LATAM', officialSource: 'https://www.itau.com.br/cartoes/escolha/g/latam-pass-visa-infinite/portfolio/', verifiedAt: '2026-09', status: 'verified' },
  { id: 'azul-visa-infinite', name: 'Azul Visa Infinite', issuer: 'Itaú', network: 'Visa Infinite', profile: 'airline', tags: ['Bom para Azul', 'Bagagem'], earning: '3 pontos Azul/US$ no Brasil; 3,5 no exterior', loyaltyProgram: 'Azul Fidelidade', loungeAccess: '2 visitas Visa Airport Companion/ano', annualFee: 'R$ 113/mês abaixo de R$ 10 mil em gastos', feeWaiver: '50% a partir de R$ 10 mil/fatura; 100% a partir de R$ 20 mil/fatura', travelBenefits: 'Categoria Azul Diamante e benefícios de bagagem, sujeitos às regras', idealFor: 'Quem voa Azul e aproveita benefícios da companhia', officialSource: 'https://www.itau.com.br/cartoes/escolha/g/azul-visa-infinite', verifiedAt: '2026-09', status: 'verified' },
  { id: 'santander-aadvantage-black', name: 'AAdvantage Black', issuer: 'Santander', network: 'Mastercard Black', profile: 'airline', tags: ['Bom para American', 'Salas VIP'], earning: '2 milhas AAdvantage/US$; +1 em compras internacionais', loyaltyProgram: 'American Airlines AAdvantage', loungeAccess: '4 visitas LoungeKey/ano; não equivale a Admirals Club', annualFee: '12 × R$ 136', feeWaiver: '50% com R$ 150 mil investidos, conforme regras', travelBenefits: 'Pontuação adicional em compras American Airlines', idealFor: 'Quem usa AAdvantage e aceita milhas concentradas', officialSource: 'https://www.santander.com.br/cartao-credito-santander/aadvantage-black', verifiedAt: '2026-09', status: 'verified' },
  { id: 'itau-private-visa', name: 'Itaú Private Visa Infinite', issuer: 'Itaú Private Bank', network: 'Visa Infinite', profile: 'travel', tags: ['Benefícios premium', 'Alta exigência'], earning: '2,5 pontos/US$ no Brasil; 3 no exterior', loyaltyProgram: 'Itaú Pontos', loungeAccess: '10 acessos Visa Airport Companion por cartão/ano', annualFee: 'Sem anuidade para cliente Private', travelBenefits: 'Benefícios Visa Infinite e serviços de viagem', idealFor: 'Cliente Private que deseja acessos e pontos flexíveis', officialSource: 'https://www.itau.com.br/private-bank/produtos-servicos/banking/cartao-visa-infinite', verifiedAt: '2026-09', status: 'verified' }
]);

export const LOUNGE_TYPES = Object.freeze([
  { id: 'priority-pass', name: 'Priority Pass', explanation: 'Associação independente de aeroportos e companhias. A entrada é validada pelo cartão digital ou físico; visitas grátis, cobranças e convidados seguem seu plano ou emissor. Confira a sala e o terminal no aplicativo antes de viajar.', officialSource: 'https://www.prioritypass.com/en-GB/conditions-of-use', verifiedAt: '2026-09', status: 'verified' },
  { id: 'loungekey', name: 'Mastercard Airport Experiences / LoungeKey', explanation: 'Cartões Mastercard elegíveis usam o site/app ou cartão cadastrado. O banco emissor define quantas visitas são cortesia; convidados podem consumir visitas ou gerar cobrança. Consulte “Complimentary Visits” no aplicativo.', officialSource: 'https://airport.mastercard.com/en/faq', verifiedAt: '2026-09', status: 'verified' },
  { id: 'visa', name: 'Visa Airport Companion', explanation: 'O aplicativo reúne salas e experiências para cartões Visa elegíveis. O acesso a salas é para Visa Infinite, mas gratuidades e convidados dependem do emissor. Verifique QR code, terminal e condições no app.', officialSource: 'https://www.visa.com.br/sobre-a-visa/vac.html', verifiedAt: '2026-09', status: 'verified' },
  { id: 'airline', name: 'Salas de companhias aéreas', explanation: 'Exemplo: LATAM VIP Lounge no GRU T3 atende viajantes em cabine ou categoria elegível; alguns cartões LATAM Pass também dão acesso quando se voa LATAM. Companhia, voo e acompanhante alteram a regra.', officialSource: 'https://www.gru.com.br/pt/passageiro/descubra-gru/conforto/salas-vip', verifiedAt: '2026-09', status: 'verified' },
  { id: 'independent', name: 'Salas independentes', explanation: 'Exemplo: Plaza Premium no GIG T2 oferece compra direta e pode aceitar parceiros. Não presuma que toda unidade participa da mesma rede; confirme a unidade, o terminal e o preço antes do embarque.', officialSource: 'https://www.riogaleao.com/passageiros/explore-riogaleao/salas-vip/plaza-premium-lounge/', verifiedAt: '2026-09', status: 'verified' }
]);

export const UPGRADE_METHODS = Object.freeze([
  { id: 'advance', title: 'Upgrade pago antes do voo', summary: 'A companhia pode oferecer uma cabine superior após a compra.', detail: 'Compare o preço total com uma passagem já vendida nessa cabine e confirme quais benefícios entram na nova tarifa.' },
  { id: 'checkin', title: 'Oferta no check-in', summary: 'Uma oferta pode aparecer perto da partida.', detail: 'Preço e disponibilidade dependem do voo. Confirme bagagem, sala VIP e regras da tarifa antes de aceitar.' },
  { id: 'miles', title: 'Upgrade com milhas ou pontos', summary: 'Alguns programas permitem usar saldo para mudar de cabine.', detail: 'A tarifa comprada pode precisar ser elegível e o assento para upgrade é separado do assento à venda. Compare com um resgate direto na cabine desejada.' },
  { id: 'status', title: 'Upgrade por status ou benefício', summary: 'Algumas condições de programa podem dar acesso a solicitações ou prioridade.', detail: 'A elegibilidade, a ordem de prioridade e a confirmação dependem das regras da companhia. Não conte com o upgrade como parte garantida da viagem.' }
]);

export const AIRLINE_UPGRADE_EXAMPLES = Object.freeze([
  { airline: 'LATAM', method: 'Trechos de cortesia', eligibleRouteCabin: 'Premium Economy ou Premium Business em voos LATAM elegíveis', timing: 'Solicitação em Minhas viagens ou no app; confirmação pode chegar 12 h antes ou no aeroporto', milesRequired: 'Trechos de cortesia por status ou cartão elegível, não milhas', restrictions: 'Tarifa mínima varia por rota; depende de assento disponível e prioridade', officialSource: 'https://www.latamairlines.com/br/pt/central-ajuda/perguntas/latam-pass/beneficios/upgrade-cabine', verifiedAt: '2026-09', status: 'verified' },
  { airline: 'TAP Air Portugal', method: 'Com milhas Miles&Go', eligibleRouteCabin: 'Economy para Business em voos elegíveis', timing: 'Antecipado, dias antes ou Last Minute no portão para categorias elegíveis', milesRequired: 'Tabela por zona e por trecho; consulte valor da rota', restrictions: 'Sem tarifa de grupo; disponibilidade limitada mesmo em voos não lotados', officialSource: 'https://points-storefront.flytap.com/pt-ve/miles-and-go/utilizar-milhas/upgrade-com-milhas', verifiedAt: '2026-09', status: 'verified' },
  { airline: 'TAP Air Portugal', method: 'Preço fixo ou leilão', eligibleRouteCabin: 'Business ou Economy Prime conforme oferta', timing: 'Gestão da reserva, check-in ou convite para licitação', milesRequired: 'Pagamento em dinheiro ou milhas quando a oferta permitir', restrictions: 'Elegibilidade por bilhete/rota; condições da tarifa original permanecem', officialSource: 'https://points-storefront.flytap.com/pt-ve/ajuda/perguntas-frequentes', verifiedAt: '2026-09', status: 'verified' },
  { airline: 'TAP Air Portugal', method: 'Benefício Navigator', eligibleRouteCabin: 'Economy para Business', timing: 'Solicitar até 72 h antes; resposta até 24 h antes', milesRequired: '2 upgrades por período anual de qualificação', restrictions: 'Apenas titular Navigator, tarifa elegível e assento disponível', officialSource: 'https://www.flytap.com/pt-br/gerenciar-reserva/extras/upgrades/gratuito', verifiedAt: '2026-09', status: 'verified' },
  { airline: 'Delta Air Lines', method: 'SkyMiles', eligibleRouteCabin: 'Cabine superior em voos Delta elegíveis', timing: 'Durante a compra ou depois em Minhas viagens/app', milesRequired: 'Preço em milhas exibido para o voo; variável', restrictions: 'Delta Basic excluída; oferta depende de voo e assentos', officialSource: 'https://www.delta.com/us/en/skymiles/how-to-use-miles/upgrades-and-more', verifiedAt: '2026-09', status: 'verified' },
  { airline: 'American Airlines', method: 'Upgrade por status', eligibleRouteCabin: 'Cabine superior em rotas elegíveis da América do Norte', timing: 'Solicitação automática ou lista de espera conforme status', milesRequired: 'Benefício de status, sem garantia de confirmação', restrictions: 'Assentos e regras dependem de rota, status e bilhete', officialSource: 'https://www.aa.com/web/i18n/aadvantage-program/answers-support/upgrades-for-status-members.html', verifiedAt: '2026-09', status: 'verified' }
]);

const airport = (iata, terminals, lounge, source, connectionNotes = null) => ({ iata, terminals, lounges: [{ name: lounge.name, terminal: lounge.terminal, networks: lounge.networks || [], eligibility: lounge.eligibility, officialSource: lounge.source || source, verifiedAt: '2026-09', status: 'verified' }], connectionNotes, officialSource: source, verifiedAt: '2026-09', status: 'verified' });
export const AIRPORT_GUIDES = Object.freeze([
  { ...airport('GRU', ['T1', 'T2', 'T3'], { name: 'LATAM VIP Lounge', terminal: 'T3, mezanino internacional', eligibility: 'Cabine, status ou cartão LATAM Pass elegível; voo e acompanhantes condicionais' }, 'https://www.gru.com.br/pt/passageiro/descubra-gru/conforto/salas-vip', 'Verifique se sua conexão exige troca de terminal e novo controle de segurança.'), lounges: [
    { name: 'LATAM VIP Lounge', terminal: 'T3, mezanino internacional', networks: [], eligibility: 'Cabine, status ou cartão LATAM Pass elegível; voo e acompanhantes condicionais', officialSource: 'https://www.gru.com.br/pt/passageiro/descubra-gru/conforto/salas-vip', verifiedAt: '2026-09', status: 'verified' },
    { name: 'W Premium Lounge', terminal: 'T3, embarque internacional', networks: ['LoungeKey', 'Priority Pass', 'Visa Airport Companion'], eligibility: 'Programa e cartão elegíveis; visitas e convidados dependem do emissor', officialSource: 'https://www.gru.com.br/pt/passageiro/descubra-gru/conforto/salas-vip', verifiedAt: '2026-09', status: 'verified' }
  ] },
  { ...airport('GIG', ['T2'], { name: 'Plaza Premium Lounge — doméstico', terminal: 'T2, piso 1, mezanino após o raio-X', eligibility: 'Compra avulsa ou programa aceito; confira a unidade e o cartão' }, 'https://www.riogaleao.com/passageiros/explore-riogaleao/salas-vip/plaza-premium-lounge/'), lounges: [
    { name: 'Plaza Premium Lounge — doméstico', terminal: 'T2, piso 1, mezanino após o raio-X', networks: ['Priority Pass', 'LoungeKey'], eligibility: 'Compra avulsa ou programa aceito; confirme a unidade e o cartão', officialSource: 'https://www.riogaleao.com/passageiros/explore-riogaleao/salas-vip/plaza-premium-lounge/', verifiedAt: '2026-09', status: 'verified' },
    { name: 'Plaza Premium Lounge — internacional', terminal: 'T2, piso 3, embarque internacional', networks: ['Priority Pass', 'LoungeKey'], eligibility: 'Compra avulsa ou programa aceito; confirme a unidade e o cartão', officialSource: 'https://www.riogaleao.com/passageiros/explore-riogaleao/salas-vip/plaza-premium-lounge/', verifiedAt: '2026-09', status: 'verified' },
    { name: 'Plaza Premium Lounge — área pública', terminal: 'T2, piso 1, mezanino antes do raio-X', networks: ['Priority Pass', 'LoungeKey'], eligibility: 'Compra avulsa ou programa aceito; confirme a unidade e o cartão', officialSource: 'https://www.riogaleao.com/passageiros/explore-riogaleao/salas-vip/plaza-premium-lounge/', verifiedAt: '2026-09', status: 'verified' }
  ] },
  airport('BSB', ['Terminal de passageiros'], { name: 'Sala VIP Express', terminal: 'Área de embarque doméstico; confira a unidade próxima ao seu portão', eligibility: 'Formas de acesso e convidados: confirmar com a sala', source: 'https://www.bsb.aero/salavip/express/contato' }, 'https://www.bsb.aero/salavip/express/contato'),
  airport('JFK', ['T1', 'T4', 'T5', 'T7', 'T8'], { name: 'Delta Sky Club', terminal: 'T4, saguões A e B', eligibility: 'Passageiros Delta elegíveis; regra de cartão/status deve ser conferida' }, 'https://www.jfkairport.com/explore-jfk/terminals/terminal-4', 'AirTrain conecta terminais; confirme o terminal da companhia.'),
  airport('MIA', ['Saguões D, E, F, G, H e J'], { name: 'American Airlines Admirals Club', terminal: 'Saguão D', eligibility: 'Cabine, status ou associação elegível; não basta cartão AAdvantage brasileiro' }, 'https://www.miami-airport.com/clubs-and-lounges.asp'),
  airport('LHR', ['T2', 'T3', 'T4', 'T5'], { name: 'No1 Lounge', terminal: 'T2', eligibility: 'Reserva/acesso conforme condições da unidade e parceiro', source: 'https://www.heathrow.com/at-the-airport/lounges-hotels-spas/terminal-2/no1-lounges' }, 'https://www.heathrow.com/at-the-airport/lounges-hotels-spas/terminal-2/no1-lounges'),
  airport('CDG', ['T1', 'T2', 'T3'], { name: 'Air France Business Lounge', terminal: 'T2E, halls K, L e M', eligibility: 'Cabine ou status Air France/KLM elegível; confirme hall do voo', source: 'https://corporate.airfrance.com/en/press-releases/air-france-presents-new-culinary-creations-yves-camdeborde-its-long-haul-lounges' }, 'https://corporate.airfrance.com/en/press-releases/air-france-presents-new-culinary-creations-yves-camdeborde-its-long-haul-lounges'),
  airport('MAD', ['T1', 'T2', 'T3', 'T4', 'T4S'], { name: 'Sala VIP Cibeles', terminal: 'T1, embarque não Schengen', eligibility: 'Compra direta; somente com cartão de embarque T1', source: 'https://www.aena.es/en/madrid-barajas-adolfo-suarez/vip-services/vip-lounge/cibeles-vip-lounge.html' }, 'https://www.aena.es/en/madrid-barajas-adolfo-suarez/vip-services/vip-lounge/cibeles-vip-lounge.html'),
  airport('LIS', ['T1', 'T2'], { name: 'Lounge ANA', terminal: 'T1, área Schengen antes do controle de passaportes', eligibility: 'Compra direta ou acordo elegível; conferir horário e lotação' }, 'https://store.ana.pt/pt_PT/lisboa/lounge/ALS-2.html'),
  airport('FCO', ['T1', 'T3'], { name: 'Plaza Premium Lounge', terminal: 'T3, área E não Schengen', networks: ['DragonPass'], eligibility: 'Compra direta ou programa elegível; conferir acordo vigente' }, 'https://www.adr.it/web/aeroporti-di-roma-en/plaza-premium-lounge-t3'),
  airport('DXB', ['T1', 'T2', 'T3'], { name: 'Emirates Lounges', terminal: 'T3, portões C', eligibility: 'Cabine ou status Emirates elegível; confirmar convidados e voo' }, 'https://dubaiairports.ae/experiences/shops/details/emirates-lounge')
]);
